name: Docker Deploy (Production)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - "src/**"
      - "client/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: docker-compose build

      # Example: Push image to Docker Hub or cloud registry
      # (Add your repository and authentication)
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Push backend image
      #   run: docker tag aviator-game_backend yourdockerhub/aviator-game-backend:latest && docker push yourdockerhub/aviator-game-backend:latest